apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-config-server
  template:
    metadata:
      labels:
        app: springboot-config-server
    spec:
      containers:
        - name: app
          image: narramadan/spring-multi-module-consul-config-config-server
          ports:
            - containerPort: 8800
          imagePullPolicy: Always
          env:
            - name: spring.profiles.active
              #value: "native"
              value: "git"
            - name: spring.cloud.consul.host
              value: "$(CONSUL_SERVER_SVC_SERVICE_HOST)"
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-config-server-svc
spec:
  selector:
    app: springboot-config-server
  ports:
    - port: 8800
      targetPort: 8800
  type: LoadBalancer