# Set config.import - https://docs.spring.io/spring-cloud-config/docs/3.0.0/reference/html/#config-data-import
spring:
  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    config:
      fail-fast: true
      name: common, ${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include: refresh, beans, env

---
spring:
  profiles: dev

server:
  port : 8081