spring:
  cloud:
    consul:
      host: 127.0.0.1
      discovery:
        prefer-ip-address: true
        health-check-critical-timeout: "1m"
---

spring:
  profiles: dev

server:
  port : 8082

service:
  name: Service B - Dev

---

spring:
  profiles: prod

server:
  port : 8080

service:
  name: Service B - Prod