spring:
  cloud:
    consul:
      host: 127.0.0.1
      discovery:
        prefer-ip-address: true
        health-check-critical-timeout: "1m"

serviceb:
  url: http://service-b

servicec:
  url: http://service-c
---

spring:
  profiles: dev

server:
  port : 8081

---

spring:
  profiles: prod

server:
  port : 8080