spring:
  application:
    name: service-c

# Set config.import - https://docs.spring.io/spring-cloud-config/docs/3.0.0/reference/html/#config-data-import
  config:
    import: "optional:configserver:"