spring:
  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    config:
      fail-fast: true
      name: common, ${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include: refresh, beans, env

---
spring:
  config:
    activate:
      on-profile: dev

server:
  port : 8083