spring:

  cloud:

    config:
      server: 
        encrypt:
          enabled: true

    consul:
      host: 127.0.0.1
      discovery:        
        instanceId: "${spring.application.name}-${server.port}-${spring.cloud.client.ip-address}"
        prefer-ip-address: true
        health-check-critical-timeout: "1m"

server:
  port : 8800